services:
  postgres:
    image: postgres:16-alpine
    container_name: notipush-postgres
    environment:
      POSTGRES_USER: notipush
      POSTGRES_PASSWORD: notipush_secret
      POSTGRES_DB: notipush
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U notipush"]
      interval: 5s
      timeout: 3s
      retries: 5

  nats:
    image: nats:2.10-alpine
    container_name: notipush-nats
    command: ["--jetstream", "--store_dir", "/data", "-m", "8222"]
    ports:
      - "4222:4222"
      - "8222:8222"
    volumes:
      - natsdata:/data
    healthcheck:
      test: ["CMD", "nats-server", "--signal", "ldm"]
      interval: 10s
      timeout: 3s
      retries: 5

volumes:
  pgdata:
  natsdata:
